services:
  frontend:
    build:
      target: dev
      args:
        - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
        - NEXT_PUBLIC_ALCHEMY_API_KEY=${NEXT_PUBLIC_ALCHEMY_API_KEY}
        - NEXT_PUBLIC_PIMLICO_API_KEY=${NEXT_PUBLIC_PIMLICO_API_KEY}
        - NEXT_PUBLIC_WEB3AUTH_CLIENT_ID=${NEXT_PUBLIC_WEB3AUTH_CLIENT_ID}
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./aa-front:/app
      - /app/node_modules

  backend:
    build:
      context: ./api
      target: dev
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - PORT=4000
      - NEXT_PUBLIC_NODE_ENV=development
      - FRONTEND_URL=http://frontend:3000
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - PAYMASTER_PRIVATE_KEY=${PAYMASTER_PRIVATE_KEY}
      - PAYMASTER_ADDRESS=${PAYMASTER_ADDRESS}
    volumes:
      - ./api:/app
      - /app/node_modules
