services:
  frontend:
    build:
      target: runner
      args:
        - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
        - NEXT_PUBLIC_ALCHEMY_API_KEY=${NEXT_PUBLIC_ALCHEMY_API_KEY}
        - NEXT_PUBLIC_PIMLICO_API_KEY=${NEXT_PUBLIC_PIMLICO_API_KEY}
        - NEXT_PUBLIC_WEB3AUTH_CLIENT_ID=${NEXT_PUBLIC_WEB3AUTH_CLIENT_ID}
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
  backend:
    build:
      target: runner
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_NODE_ENV=production
      - FRONTEND_URL=http://frontend:3000
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - PAYMASTER_PRIVATE_KEY=${PAYMASTER_PRIVATE_KEY}
      - PAYMASTER_ADDRESS=${PAYMASTER_ADDRESS}
