# docker-compose.yml (開発用 - シンプル版)
services:
  frontend:
    build:
      context: .
      dockerfile: aa-front/Dockerfile
      args:
        - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
        - NEXT_PUBLIC_ALCHEMY_API_KEY=${NEXT_PUBLIC_ALCHEMY_API_KEY}
        - NEXT_PUBLIC_PIMLICO_API_KEY=${NEXT_PUBLIC_PIMLICO_API_KEY}
        - NEXT_PUBLIC_WEB3AUTH_CLIENT_ID=${NEXT_PUBLIC_WEB3AUTH_CLIENT_ID}
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./aa-front:/app
      # node_modules と .next はイメージ内のものを使う
      - /app/node_modules
      - /app/.next
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - PAYMASTER_PRIVATE_KEY=${PAYMASTER_PRIVATE_KEY}
      - PAYMASTER_ADDRESS=${PAYMASTER_ADDRESS}
    volumes:
      - ./api:/app
      - /app/node_modules
      # - /app/dist # ビルド出力がある場合はコメント解除
    command: npm run dev
