services:
  frontend:
    build:
      context: ./aa-front
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    volumes:
      - ./aa-front:/app

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - PORT=4000
      - FRONTEND_URL=http://frontend:3000
    env_file:
      - ./.env
    volumes:
      - ./api:/app

  db:
    image: postgres:15-alpine
    container_name: postgres_pta
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  postgres_data:
