services:
  frontend:
    build:
      context: .
      dockerfile: aa-front/Dockerfile
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: unless-stopped