# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: aa-front/Dockerfile
      args:
        - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
        - NEXT_PUBLIC_ALCHEMY_API_KEY=${NEXT_PUBLIC_ALCHEMY_API_KEY}
        - NEXT_PUBLIC_PIMLICO_API_KEY=${NEXT_PUBLIC_PIMLICO_API_KEY}
        - NEXT_PUBLIC_WEB3AUTH_CLIENT_ID=${NEXT_PUBLIC_WEB3AUTH_CLIENT_ID}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://frontend:3000
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - PAYMASTER_PRIVATE_KEY=${PAYMASTER_PRIVATE_KEY}
      - PAYMASTER_ADDRESS=${PAYMASTER_ADDRESS}
    restart: unless-stopped