services:
  frontend:
    build:
      context: .
      dockerfile: aa-front/Dockerfile
      target: ${NODE_ENV:-runner}
      args:
        - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
        - NEXT_PUBLIC_ALCHEMY_API_KEY=${NEXT_PUBLIC_ALCHEMY_API_KEY}
        - NEXT_PUBLIC_PIMLICO_API_KEY=${NEXT_PUBLIC_PIMLICO_API_KEY}
        - NEXT_PUBLIC_WEB3AUTH_CLIENT_ID=${NEXT_PUBLIC_WEB3AUTH_CLIENT_ID}
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - ${NODE_ENV:+./aa-front:/app}
      - ${NODE_ENV:+/app/node_modules}
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: ${NODE_ENV:-runner}
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_PUBLIC_NODE_ENV=${NODE_ENV:-production}
      - FRONTEND_URL=http://frontend:3000
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - PAYMASTER_PRIVATE_KEY=${PAYMASTER_PRIVATE_KEY}
      - PAYMASTER_ADDRESS=${PAYMASTER_ADDRESS}
    volumes:
      - ${NODE_ENV:+./api:/app}
      - ${NODE_ENV:+/app/node_modules}
    restart: unless-stopped
