name: Deploy Backend

on:
  push:
    branches: [main, master]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [main, master, develop]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      secrets: 'read'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: aa-dashboard-457316
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Check GCloud Auth Status
        shell: bash
        run: |
          echo "--- 1. Check Active Account ---"
          gcloud auth list
          
          echo "--- 2. Check Project ---"
          gcloud config list
          
          echo "--- 3. Confirm Secret Access ---"
          gcloud secrets versions access latest --secret=ALCHEMY_API_KEY --project=aa-dashboard-457316 > /dev/null && echo "Secret access successful" || echo "Secret access failed"

      - name: Deploy to Cloud Run
        env:
          REGION: 'asia-northeast1'
          BACKEND_SERVICE_NAME: 'backend-api'
          PAYMASTER_ADDRESS: '0x415b4ceC5cf512CeDBE09C12081A0b75E13854Ff'
        run: |
          NON_SECRET_ENV_VARS="NODE_ENV=production,PAYMASTER_ADDRESS=${PAYMASTER_ADDRESS}"
          SECRET_VARS="ALCHEMY_API_KEY=ALCHEMY_API_KEY:latest,PAYMASTER_PRIVATE_KEY=PAYMASTER_PRIVATE_KEY:latest"

          echo "Deploying to Cloud Run: ${BACKEND_SERVICE_NAME}"
          gcloud run deploy ${BACKEND_SERVICE_NAME} \
            --project=aa-dashboard-457316 \
            --source ./api \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated \
            --port 4000 \
            --update-env-vars "${NON_SECRET_ENV_VARS}" \
            --update-secrets="${SECRET_VARS}"