name: Deploy Backend

on:
  push:
    branches: [main, master]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [main, master, develop]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      secrets: 'read'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Verify authentication'
        run: |
          gcloud auth list
          gcloud config list
          gcloud projects describe aa-dashboard-457316 --format='value(projectNumber)'

      - name: Deploy to Cloud Run
        env:
          REGION: 'asia-northeast1'
          BACKEND_SERVICE_NAME: 'backend-api'
          PAYMASTER_ADDRESS: '0x415b4ceC5cf512CeDBE09C12081A0b75E13854Ff'
        run: |
          NON_SECRET_ENV_VARS="NODE_ENV=production,PAYMASTER_A
