name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]  # 新しいPRと更新時に実行

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      # git diff操作を可能にするためにコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 正確な差分のために完全な履歴を取得

      - name: Run Code Review with Claude
        id: code-review
        uses: anthropics/claude-code-action@beta
        with:
          # レビューの焦点領域を定義
          prompt: "PR変更をレビューしてください。コード品質、潜在的なバグ、パフォーマンスの問題に焦点を当ててください。適切な改善点を提案してください。"

          # より安全なレビュー操作のための限定ツール
          allowed_tools: [
            "Bash(git diff --name-only HEAD~1)",  # 変更されたファイルをリスト
            "Bash(git diff HEAD~1)",              # 実際の変更を確認
            "View", # ファイル内容の読み取り
            "GlobTool",                          # 関連ファイルの検索
            "GrepTool"                           # パターンの検索
          ]

          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}